require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"

require "user.alpha"
require "user.nvim-tree"
require "user.project"
require "user.bufferline"
require "user.lualine"

require "user.glow"
require "user.toggleterm"
require "user.floaterm"

require "user.lastplace"
require "user.neoscroll"
require "user.colorizer"
require "user.colorpicker"
-- require "user.illuminate"
require "user.gitsigns"
require "user.indentline"
require "user.autopairs"
require "user.surround"
require "user.chalk"
require "user.comment"
require "user.hop"
-- require "user.matchup"
require "user.navigator"
require "user.multi"

require "user.cmp"
require "user.lsp"
require "user.copilot"
require "user.telescope"
require "user.treesitter"

require "user.whichkey"
require "user.autocommands"
